### PR TITLE
fix: profile page bug and minor UI overflows

### PR DESCRIPTION
**Pull request by ApurvaSawant11**
In this PR, I have made some UI changes and fixed UserProfile page bug

### CODE REVIEW

**Comment by Dev-AkshatGupta** [comment]
You almost made it like a notes app on steroids with the capability of the social media .Jokes apart.
Kudos to you for such amazing features though.

**Review by Dev-AkshatGupta — APPROVED** [review]
Kudos to you amazing work apoorva
Great code functions in the app and an amazing UI.

**Comment by foolhardy21** [comment]
On bookmarks page, you can add spacing between two bookmark posts.
v4

**Review by foolhardy21 — APPROVED** [review]
The code also looks good. Nothing to suggest. Good work.

**Comment by ApurvaSawant11** [comment]
> On bookmarks page, you can add spacing between two bookmark posts. v4

Thanks for pointing it out.  I have made the changes

**Comment by ApurvaSawant11** [comment]
> You almost made it like a notes app on steroids with the capability of the social media .Jokes apart. Kudos to you for such amazing features though.

😂😂This is what happens when I am in full Josh. Thank you so much :)

**Comment by ApurvaSawant11** [comment]
> Kudos to you amazing work apoorva Great code functions in the app and an amazing UI.

Again thank you so much! Really happy that you liked the features and UI 😄

**Pull request merged**
